import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import torch
from models.hnn_core import ChristLeeHNN


def test_gauge_symmetry(model, sample_state):
    """
    Verifies that H(zeta) is invariant under the gauge transformation:
    delta_theta = kappa, delta_lambda = -kappa [cite: 145, 150]
    """
    kappa = 0.05
    state_a = sample_state.clone()

    # Apply the gauge transformation generated by the zero mode [cite: 142]
    state_b = state_a.clone()
    state_b[0, 2] += kappa  # theta shift
    state_b[0, 4] -= kappa  # lambda shift [cite: 142, 150]

    _, h_a = model(state_a)
    _, h_b = model(state_b)

    diff = torch.abs(h_a - h_b).item()
    print(f"Gauge Symmetry Invariance Error: {diff:.8f}")


# --- ADD THESE LINES TO RUN THE TEST ---
if __name__ == "__main__":
    # 1. Initialize the model
    my_model = ChristLeeHNN()

    # 2. Create a dummy state: [r, Pr, theta, Ptheta, lambda, rho]
    # We use a tensor with size (1, 6) to represent one state batch
    dummy_state = torch.tensor([[1.5, 0.1, 0.0, 0.0, 0.0, 0.0]], dtype=torch.float32)

    # 3. Call the function
    test_gauge_symmetry(my_model, dummy_state)